### ISSUE TITLE
switch to GTK4

### ISSUE THREAD

**Issue by LordMZTE** [capy-ui/capy#17]
GTK3 has been pretty much discontinued now in favor of GTK4, so maybe zgt should upgrade.

**Comment by mgord9518** [comment]
Or maybe add it and dlopen whatever is present on launch? Then (slightly) older systems would stay compatible

**Comment by zenith391** [comment]
> Or maybe add it and dlopen whatever is present on launch? Then (slightly) older systems would stay compatible

That's a good idea although it could be complex to add code for every function that needs to be loaded. But Zig comptime should allow to automatize that.

**Comment by malespiaut** [comment]
I was about to open the same issue. I would love to contribute and do it myself, but I'm far from being a GTK expert.
