### ISSUE TITLE
`TextArea` not implemented on win32 backend

### ISSUE THREAD

**Issue by tomasz-lisowski** [capy-ui/capy#25]
I followed the instructions, but I seem to get these errors on Windows. On Debian the exact same setup seems to work fine. Any suggestions on how to fix this? I am using capy version `f926cfb8855f83942d7291be3179f82db7827ba9`.
```
.\.zigmod\deps\git\github.com\zenith391\capy\src\text.zig:11:19: error: container '.capy.backend' has no member called 'TextArea'
    peer: ?backend.TextArea = null,
                  ^
.\.zigmod\deps\git\github.com\zenith391\capy\src\button.zig:38:17: error: no member named 'setEnabled' in struct '.capy.backends.win32.backend.Button'
        peer.*.?.setEnabled(newValue);
                ^
```

**Comment by zenith391** [comment]
It's because currently `TextArea` hasn't yet been implemented in the win32 backend. Though I should be able to implement it next week.

**Comment by Ristovski** [comment]
@zenith391 Any progress on this? Seems like the author closed this as completed even though its still an issue on master.

**Comment by MeerMusik** [comment]
Hello and Sorry in advance for "spamming" everyone! Question for zenith391:

What is the Reason that ```TextArea``` has no ```WIN32 Backend```? Simply lack of time? Priority Backlog? One or multiple of the existing Issues in the Zig Language itself? Not (yet) existing Features = WIN32-Dependencies in Capy that need to be implemented first?

Thank you!

**Comment by zenith391** [comment]
Lack of time and the fact that there are currently some features more important than it. But I'll get to it soon enough.
