### ISSUE TITLE
Qt Backend

### ISSUE THREAD

**Issue by kassane** [capy-ui/capy#30]
Obviously interop c++ ​​is quite complex.
However, perhaps a possibility begins to emerge.

Qt widgets (C binding)
- https://github.com/sammonius/qtc/issues/2

**Comment by zenith391** [comment]
Thanks for addressing the question but I do not think this would fit Capy. If we include a full multi-platform library inside of it, might as well skip Capy and just use a Qt wrapper directly.
So I don't think I'll implement that as this would essentially make Capy a shim over Qt.

**Comment by mgord9518** [comment]
I think this might be worth opening back up for the use-case of Qt-based *nix DEs. I've started working on some rudimentary Qt bindings to C and Zig, and I'd be happy to include it as an alternative backend. Qt may be a cross-platform toolkit, but it is *the* native toolkit for KDE, LxQt, etc.

**Comment by mgord9518** [comment]
I've started a [fork](https://github.com/mgord9518/capy-qt) where I will be working on this. Once it becomes usable it would be really nice to see it integrated upstream, but otherwise I'm fine with maintaining it separately
