### ISSUE TITLE
Binding text of TextArea with Gtk doesn't update text on editing

### ISSUE THREAD

**Issue by Bnyro** [capy-ui/capy#37]
Hey,
first of all thanks for spending so much efforts into the project, it's my favorite one for building desktop apps :)

I've been trying to build a very simple [text editor](https://github.com/Bnyro/zedit) and came across the issue that when the user edits a text inside a text area, the text doesn't update inside the bound `DataWrapper`.
However, when setting the text via `DataWrapper#set` the text inside the `TextArea` updates properly and the text can be correctly read with `DataWrapper#get`. I will leave a small example program below.

```zig
const std = @import("std");
const capy = @import("capy");

var text = capy.DataWrapper([]const u8).of("");

pub fn main() !void {
    try capy.init();

    var window = try capy.Window.init();
    var textArea = capy.TextArea(.{}).bind("text", &text);

    // Setting the text programmatically works fine and prints out correctly
    textArea.setText("Text set programmatically");
    std.debug.print("{s}", .{text.get()});

    try window.set(capy.Column(.{ .spacing = 0 }, .{
        &textArea,
        capy.Button(.{ .label = "Print", .onclick = &printText }),
    }));

    window.setTitle("test");
    window.resize(800, 600);
    window.show();

    capy.runEventLoop();
}

fn printText(_: *anyopaque) anyerror!void {
    // Printing the text after the user edited the text field manually doesn't show the updated text
    std.debug.print("{s}", .{text.get()});
}

```

I have only tested this with the Gtk backend so far, thus I can't say how other backends behave.

**Comment by zenith391** [comment]
Thanks! It was due to me forgetting to implement the `changed` signal for text areas like I did for text fields.
It should now work properly

**Comment by Bnyro** [comment]
Wow, that's awesome, thank you for the fast fix! <3
