### ISSUE TITLE
Need an example on how to use Capy as a package.

### ISSUE THREAD

**Issue by malespiaut** [capy-ui/capy#50]
Hello,

I understood that the concept of packages isn't clearly defined in Zig, at least in the latest nigthly build.

Yet, I think it would help to have an example on how to use Capy as a package for a new Zig project.

Best regards.

**Comment by Damjan94** [comment]
I was struggling with this recently too. It's quite simple once you know what to do.
First, as [pointed out to me](https://ziggit.dev/t/how-to-import-from-the-zon-file/1224/2), capy has a [template](https://github.com/capy-ui/zig-template) that works with zigmod package manager.

If you want it to work with `build.zig.zon`, add capy as a dependency like so (try to build, it'll tell you the expected hash, add it after the `.url` field.
```zig
.{
	.version = "0.0.0",
	.name = "test",
	.dependencies = .{
		.capy = .{
			.url = "https://github.com/capy-ui/capy/archive/refs/heads/master.tar.gz",
		}	
	},
}
```

and in your build.zig do
```
const capy_install = @import("capy").install;
    ...
    _ = try capy_install(exe, .{});
    b.installArtifact(exe);

```

**Comment by malespiaut** [comment]
Thank you for your answer. However Zig build asks for a `.hash` field in the `.zon` file, and I don't understand yet if it's possible to skip it.

**Comment by Damjan94** [comment]
it will print the hash it expects. just paste it below the .url, so it becomes

```zig
.{
	.version = "0.0.0",
	.name = "test",
	.dependencies = .{
		.capy = .{
			.url = "https://github.com/capy-ui/capy/archive/refs/heads/master.tar.gz",
			.hash = "paste the hash that zig tells you it's expecting",
		}	
	},
}
```

you should hang around at ziggit.dev
Andrew explained it briefly [here](https://ziggit.dev/t/article-zig-package-manager-wtf-is-zon/939/2) (read the paragraph starting with "Suggested workflow ...").

**Comment by zenith391** [comment]
https://github.com/capy-ui/zig-template has been updated to use the Zig package manager. So this issue is now closed.
