### ISSUE TITLE
zig version 0.12.0-dev.2159+7916cf6f8 build changes

### ISSUE THREAD

**Issue by AdjectiveAllison** [capy-ui/capy#72]
`std.build` no longer exists. This brings up issues in `build_capy.zig`.

`std.Build.CompileStep` also no longer exists. `std.Build.Step.Compile` might be the replacement? 

I believe there were some changes to adding modules as well. 
For example, this:
```zig
    const zigimg = b.createModule(.{
        .source_file = .{ .path = prefix ++ "/vendor/zigimg/zigimg.zig" },
    });
```

Might need to be changed to this:
```zig
    const zigimg = b.createModule(.{
        .root_source_file = .{ .path = prefix ++ "/vendor/zigimg/zigimg.zig" },
    });
```

This is the same issues as reported on the template repo: https://github.com/capy-ui/zig-template/issues/10

**Comment by zenith391** [comment]
closed by 4d1778feba39949fb2569379b8ac4aabf4842478
