### ISSUE TITLE
In window capy example template throw error

### ISSUE THREAD

**Issue by dhrubrawat66** [capy-ui/capy#79]
1. i create the the project by using example template as 
    git clone https://github.com/capy-ui/zig-template
3. when i run zig build then it throws following error
 ![Screenshot 2024-03-07 201924](https://github.com/capy-ui/capy/assets/85351405/3c07b84e-66d9-4292-a33e-cfe2f21d2ae7)
5.  how can i solve it?
Note. os - window 11.

**Comment by zenith391** [comment]
Capy targets version `0.12.0-dev.2063+804cee3b9` so you should install that version of Zig.
