### ISSUE TITLE
plans for Zig 0.12 ?

### ISSUE THREAD

**Issue by FObersteiner** [capy-ui/capy#82]
Now that Zig 0.12 is out: any plans to migrate the codebase?

Haven't tried cappy before but it looks pretty cool so I wanted to fool around with it. Just tried to run the tests and the compiler throws a ton of errors at me. I started to make some adjustments to the code to progress further into the tests, and it seems like most of the 0.12 "errors" don't require severe changes (migrated types, changed field names and the like). But it would bring incompatibility with 0.11 of course.

**Comment by zenith391** [comment]
I should probably make it more explicit, but capy is following the [nominated Zig versions](https://machengine.org/about/nominated-zig/) as a way to mitigate the fact there is too much time between Zig releases.
This means I won't migrate to 0.12 yet.

**Comment by FObersteiner** [comment]
@zenith391 that's kind of a bummer but I see you have your reasons, can understand that. Zig evolving is one thing (a good one I guess), dependency management is another (not always a good fit, those two).
