### ISSUE TITLE
Website not responding

### ISSUE THREAD

**Issue by EliezerRamirezRuiz** [capy-ui/capy#84]
I have tried to look for information about this project on your website, the website is not responding, is this problem only happening to me?

I am attaching screenshots taken from my computer, although I have also tried on my mobile phone with the same result.

![image](https://github.com/capy-ui/capy/assets/83837915/66ed1092-9fc1-4bd0-8243-e94956b64821)

**Comment by zenith391** [comment]
Thanks for reporting this! The IP of the server had changed but the DNS wasn't updated. The website now fixed.

**Comment by mitteneer** [comment]
For what it's worth, I'm still getting timeouts...
