### ISSUE TITLE
Support special window mode (desktop full-screen, full-screen, etc.)

### ISSUE THREAD

**Issue by w568w** [capy-ui/capy#86]
I am working on a cross-platform screenshot app, and found capy-ui really handy. It will be very useful to allow building full-screen applications with capy-ui. 

For a full-screen app (or game), there are 2 different modes:
- **Desktop Full-screen**: A borderless full-screen window on desktop;
- **Full-screen**: An exclusive full-screen window.

As far as I know, it is [available in most platforms](https://github.com/rust-windowing/winit/blob/master/FEATURES.md). 

For full-screen and some other window features (e.g., HiDPI support, decoration toggling), I am willing to contribute.

**Comment by zenith391** [comment]
Sure, I'll add that feature in a few days time.

**Comment by zenith391** [comment]
Implemented in 6f9228f4c7e60fea07223bb1df836b8250b29ea7

**Comment by w568w** [comment]
Wow it progressed so fast, thank you for your excellent work! :smile: 

If you still have some TODOs unplanned or unfinished, please don't hesitate to tell me. I am very willing to contribute.
