### ISSUE TITLE
favicon lost on the web page

### ISSUE THREAD

**Issue by EliezerRamirezRuiz** [capy-ui/capy#89]
I found maybe a problem in the web page, it is that it does not load the favicon. It downloads when one enters the page but fails to render.

I attach evidence, as it has been verified through Microsoft edge and DuckDuckGo.

![image](https://github.com/user-attachments/assets/040a859a-0f8a-4a31-8748-e4456b839315)

**Comment by imanav10** [comment]
Hey @EliezerRamirezRuiz it might be issue from your browser side. You can try to clear caches, hope it might show.

**Comment by EliezerRamirezRuiz** [comment]
Hey @chikoYEAT, how are you?. Look I have tried at least on 3 computers and does not render the favicon but from the phone if, in fact I have deleted the cache but still nothing but the weirdest thing is that it is still rendering from the phone despite having cleared the cache. Well as you say it may be a problem of my computer or internet because when I see the web traffic I get it. Anyway thanks, in the end it does not affect the performance of the web.

**Comment by chikoYEAT** [comment]
Yeah, sometimes its related to some unknown proxy issues it fixes by itself no idea how, for example i was facing similar issue on x.com and i thought it might be occuring for other users but when, i used mobile data over wifi it worked.
