### ISSUE TITLE
Document what widgets are implemented per platform.

### ISSUE THREAD

**Issue by geon** [capy-ui/capy#95]
There should be some documentation of what widgets are implemented for each platform. I tried summarising them, but I'm sure I got some wrong. Still, something like this, perhaps?:

||win32|macOS|GTK|Android|wasm|
|--- |---|---|---|---|---|
|Button|✅|✅|✅|✅|✅|
|Canvas|✅|✅|✅|✅|✅|
|CheckBox|✅|❌|✅|❌|❌|
|Dropdown|✅|❌|✅|❌|❌|
|Image|❌|❌|❌|❌|❌|
|Label|✅|✅|✅|✅|✅|
|Menu|❌|❌|❌|❌|❌|
|Navigation|❌|❌|❌|❌|❌|
|NavigationSidebar|❌|❌|✅|❌|❌|
|Scrollable|❌|❌|❌|❌|❌|
|Slider|✅|❌|✅|❌|✅|
|Tabs|❌|❌|❌|❌|❌|
|TextArea|✅|❌|✅|❌|❌|
|TextField|✅|❌|✅|✅|✅|

**Comment by zenith391** [comment]
Thanks for the suggestion! I agree it's a clearer view of everything that works and doesn't work (and frankly, it could also help me spot what to improve on). I'll add it to the README directly.
